### PR TITLE
Update spot.js - Prettier way of finding neighboors

### PR DESCRIPTION
**Pull request by lucaspellegrinelli**
Making the "getNeighboringWalls" and "addNeighbors" a little bit prettier

### CODE REVIEW

**Comment by shiffman** [comment]
Oh, this is great!  Can you resolved the conflicts by any chance?

**Comment by ootsby** [comment]
FYI - this merge seems to have broken a few things.

**Comment by shiffman** [comment]
oops!  If anyone has a chance to take a look please do, otherwise I can roll back.

**Comment by ootsby** [comment]
It's up to you. I'll have a fix ready in an hour or so but it'll be a complete rewrite of this rather than few tweaks.

**Pull request merged**
