### PR TITLE
Added basic GUI controls with stepping, restart, diagonals option. Node info. Refactoring.

### PR DESCRIPTION
**Pull request by ootsby**
I don't know if you'd rather take this easy merge and make #4 more difficult or go in order and bounce this back to resolve conflicts after that one. I'm easy either way.

### CODE REVIEW

**Comment by shiffman** [comment]
Ooops, I ended up going in order and merged #4.  Can you refactor this?

**Comment by ootsby** [comment]
Yeah, I'll get onto it later this evening. Early stage changes to this sort of quick and dirty code are always going to end up with breaking merges.

**Comment by ootsby** [comment]
Okay, done. I think the rendering stuff needs pulling out of Spot and put into a MapRenderer or similar but this will do for now before more pull requests pile up.

**Comment by shiffman** [comment]
This is great, thank you!  I think it might be a nice improvement to change the code to use `p5.dom.js` for the interface elements. See #13.  I also noticed there are some issues with maybe stroke around the buttons and text now that some of the map rendering has changed.

**Comment by ootsby** [comment]
Sure. I'd have no major objections to replacing the UI. The reasons I just hacked together some UI code are just:
1. I've no idea what UI libs are around or which you'd prefer.
2. I think it's generally better for teaching examples to be self-contained both for understanding and to be easier to get up and running.

**Comment by shiffman** [comment]
Thanks!  Yes, p5.dom.js is a library I teach with that goes well with the main p5.js canvas rendering so it's a great choice for here.  Thanks for getting this started!

**Pull request merged**
