### PR TITLE
Add maze generation algorithm and setting

### PR DESCRIPTION
**Pull request by Hyftar**
This pull request adds an algorithm to generate a maze to test the A* algorithm with.

To use the maze generation, just change `obstaclesOption` to `1` in `sketch.js` ([line 17](https://github.com/Hyftar/AStar/blob/Maze-generation/sketch.js#L17)).

### CODE REVIEW

**Comment by shiffman** [comment]
This is great, thank you!  Can you resolve the conflicts by any chance?

**Comment by Hyftar** [comment]
Conflicts resolved, now using the MapFactory among with other map generators.

**Comment by TheEyeOfBrows** [comment]
The maze is super fun to watch!

Couple notes you may want to check:
* index.html is missing the new mazemap.js
* the addition to spot.js kinda breaks the searchmap.js generator (too many walls). Could that be moved into the mazemap.js generator somehow?

**Comment by Hyftar** [comment]
@TheEyeOfBrows I forgot about `index.html`, I'll add it now.

Unsure how I broke the `searchmap.js` generator since the only thing I added (unless I forgot to remove something) was `this.visited`, but I'll look into it.

**Comment by ootsby** [comment]
Looks like the "if (random(1) < percentWalls) {" bit has been accidentally left in spot.js from the previous merge. I can't see that it's necessary for the mazegen as it sets isWall to true in the spot constructor.

**Comment by shiffman** [comment]
Is this working or should I hold off on merging?

**Comment by Hyftar** [comment]
Give me a minute, I'll push another commit

**Comment by Hyftar** [comment]
@shiffman Everything should be fixed, feel free to merge!

**Comment by shiffman** [comment]
Great!  I'm taking a very easygoing hands-off approach and just merging stuff here without reviewing!  (You guys are better at this than me anyway.) I can always roll back if things go awry!

**Pull request merged**
